name: Run Node.js App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-node-app:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Change this to the Node.js version your app requires

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run the Node.js app
    - name: Run the app
      run: node .
